CREATE TABLE PLACE_FA.PLACE (
  PLACE_ID VARCHAR(36) NOT NULL,
  PRIMARY KEY (PLACE_ID)
);

CREATE TABLE PLACE_FA.GEO_CODE (
  GEO_CODE_ID VARCHAR(36) NOT NULL,
  ICAO_CODE VARCHAR(500),
  PRIMARY KEY (GEO_CODE_ID)
);

CREATE TABLE PLACE_FA.PLACE_GEO_CODE (
  PLACE_ID  VARCHAR(36) NOT NULL,
  GEO_CODE_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PLACE_ID) REFERENCES PLACE_FA.PLACE(PLACE_ID),
  FOREIGN KEY(GEO_CODE_ID) REFERENCES PLACE_FA.GEO_CODE(GEO_CODE_ID)
);